imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    validation: { enable_annotations: true }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

# Assetic configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
            less:
                node: /usr/local/bin/node
                node_paths: [/usr/local/lib/node_modules]
                apply_to: ".less"
            cssrewrite: ~

#braincrafted bootstrap configuration
braincrafted_bootstrap:
    output_dir:
    assets_dir: '%kernel.root_dir%/../vendor/twbs/bootstrap'
    jquery_path: '%kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js'
    css_preprocessor: less # "less", "lessphp", "sass" or "none"
    fonts_dir: '%kernel.root_dir%/../web/fonts'
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: '%kernel.root_dir%/Resources/less/bootstrap.less'
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
            logo_original:
                uri_prefix:         /images/logos
                upload_destination: '%kernel.root_dir%/../web/images/logos/original'
                namer:              Choox.image_namer
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true
            logo_altered:
                uri_prefix:         /images/logos
                upload_destination: '%kernel.root_dir%/../web/images/logos/altered'
                namer:              Choox.image_namer
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true