# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    teamprovider:
        class:    ChooxBundle\Service\TeamProvider
        arguments: ["@doctrine_cache.providers.team_names_cache"]
    app.form.registration:
        class: ChooxBundle\Form\RegistrationType
        tags:
          - { alias: app_user_registration, name: form.type }
    choox.image_namer:
        class: ChooxBundle\Service\Vich\UniqueIdNamer
        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('ChooxBundle:Logo')"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
