# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    teamprovider:
        class:    AppBundle\Service\TeamProvider
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
          - { alias: app_user_registration, name: form.type }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
