<?php

namespace ChooxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogoRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class LogoRepository extends EntityRepository
{
    /**
     * Sadly this does not work yet. Symfony says I have no doctrine.
     * Need to find out how to properly use xdebug here.
     * @param $originalName
     * @return array
     */
    public function findByOriginalLogoFileName($originalName)
    {
        return $this->findBy(['originalLogo' => $originalName]);
    }

    public function findByAlteredLogoFileName($alteredName)
    {
        return $this->findBy(['alteredLogo' => $alteredName]);
    }
}
